### ISSUE TITLE
How to run with Github Workflow

### ISSUE THREAD

**Issue by DerMuffin** [Prem-ium/BingRewards#30]
Hey,

can i run this script fully automate with github workflow? So the only thing i need is to do is to collect all giftcards?

Thanks

Muffin

**Comment by NelsonDane** [comment]
No, this script does not run in GitHub Actions. If you check the readme you can see the many ways to run it. We use GitHub Actions (workflows) to build and push to our respective Docker repositories. Hope this answers your question!

**Comment by DerMuffin** [comment]
Would this be a option to add as a feature? Or is there any other possibility to run this without a paid host?

**Comment by NelsonDane** [comment]
No, this is not something that we're planning on ever adding. Of course, you can always run this on your own computer!
