### ISSUE TITLE
Add more points earning options

### ISSUE THREAD

**Issue by TatsP** [Prem-ium/BingRewards#35]
These are a few points options that can earn around 100 points daily per account, please add the functionalities to complete these tasks. 
1.) Implementation of feature to automatically complete daily videos as well as the daily available web browser pages, this will result in additional 100-150 points per account, more information regarding this will be found in the below mentioned Reddit threads.

https://reddit.com/r/MicrosoftRewards/comments/vscyfu/us_found_new_daily_points/

https://reddit.com/r/MicrosoftRewards/comments/wn1and/msn_fitness_hyper_optimization_i_aint_got_time_to/

**Comment by zera4real** [comment]
@TatsP Do you know any closed-source bots which are well-maintained and have more features than these bots?
