### ISSUE TITLE
does not work with quizzes

### ISSUE THREAD

**Issue by AinzOoalGown-fun** [Prem-ium/BingRewards#39]
https://github.com/Prem-ium/BingRewards/issues/39#issuecomment-1371043238

Thank you

**Comment by NolanMastro** [comment]
Seems you are just missing a module, you can install flask by doing 

pip install flask

or you can install the whole requirements folder by doing 

pip install -r requirements.txt

**Comment by AinzOoalGown-fun** [comment]
Thank you i can run  python main.py but i have error
 * Serving Flask app ''
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.43.77:8080
Press CTRL+C to quit
Current IPv4 Address: 77.204.146.25
Unable to get IPv6 address


Starting Bing Rewards Automation:       2023-01-04 05:55:15.193910-08:00

[WDM] - Downloading: 100%|████████████████████████████████████████████████████████| 6.58M/6.58M [00:00<00:00, 7.59MB/s]

DevTools listening on ws://127.0.0.1:10858/devtools/browser/715549fd-bd95-4c01-acb7-9755f8a6c8a8
[0104/145519.697:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[0104/145611.508:INFO:CONSOLE(31)] "Uncaught ReferenceError: jQuery is not defined", source: https://rewards.bing.com/ (31)
[0104/145849.095:INFO:CONSOLE(401)] "Uncaught ReferenceError: angular is not defined", source: https://rewards.bing.com/ (401)
[0104/145849.095:INFO:CONSOLE(460)] "Uncaught TypeError: Cannot read properties of undefined (reading 'initializePortalTelemetry')", source: https://rewards.bing.com/ (460)

file .env 
LOGIN="mymail:password"
URL=https://login.live.com/login.srf?{QUERY}
HEADLESS=True
MULTITHREADING=False
AUTO_REDEEM=False
TZ=America/Los_Angeles
TIMER=False
BROWSER=chrome
HANDLE_DRIVER=True
KEEP_ALIVE=True

Thank you -_-

**Comment by AinzOoalGown-fun** [comment]
It work but  i have error
python main.py
Current IPv4 Address: 1************
Unable to get IPv6 address


Starting Bing Rewards Automation:       2023-01-04 06:41:56.761694-08:00


DevTools listening on ws://127.0.0.1:6049/devtools/browser/29d40024-976c-4699-9699-0a313e5cfb95
Email:  a******@hotmail.fr
        Points: 81
        Cash Value:     $0.062

        PC Searches Left:       5

Message: element click intercepted: Element <a class="ds-card-sec ng-scope" ng-if="$ctrl.item.callToAction.text" aria-disabled="false" aria-label="C'est la journée du braille   Apprenez-en davantage sur ce système d'écriture tactile   10 points" tabindex="0" target="true" role="link">...</a> is not clickable at point (149, 400). Other element would receive the click: <a target="_blank" href="https://go.microsoft.com/fwlink/?LinkId=521839">...</a>
  (Session info: headless chrome=108.0.5359.125)
Stacktrace:
Backtrace:
        (No symbol) [0x0030F243]
        (No symbol) [0x00297FD1]
        (No symbol) [0x0018D04D]
        (No symbol) [0x001C28B9]
        (No symbol) [0x001C08CC]
        (No symbol) [0x001BE4CB]
        (No symbol) [0x001BD164]
        (No symbol) [0x001B32A6]
        (No symbol) [0x001D858C]
        (No symbol) [0x001B2BFF]
        (No symbol) [0x001D8804]
        (No symbol) [0x001EC9EB]
        (No symbol) [0x001D8386]
        (No symbol) [0x001B163C]
        (No symbol) [0x001B269D]
        GetHandleVerifier [0x005A9A22+2655074]
        GetHandleVerifier [0x0059CA24+2601828]
        GetHandleVerifier [0x003B8C0A+619850]
        GetHandleVerifier [0x003B7830+614768]
        (No symbol) [0x002A05FC]
        (No symbol) [0x002A5968]
        (No symbol) [0x002A5A55]
        (No symbol) [0x002B051B]
        BaseThreadInitThunk [0x76636BD9+25]
        RtlGetFullPathName_UEx [0x771A8FD2+1218]
        RtlGetFullPathName_UEx [0x771A8F9D+1165]

Message: element click intercepted: Element <a class="ds-card-sec ng-scope" ng-if="$ctrl.item.callToAction.text" aria-disabled="false" aria-label="Sondage Rewards quotidien   Choisissez votre préférence et comparez votre réponse.   10 points" tabindex="0" target="true" role="link">...</a> is not clickable at point (621, 400). Other element would receive the click: <div id="wcpConsentBannerCtrl" class="_23tra1HsiiP6cT-Cka-ycB" dir="ltr" role="alert">...</div>
  (Session info: headless chrome=108.0.5359.125)
Stacktrace:
Backtrace:
        (No symbol) [0x0030F243]
        (No symbol) [0x00297FD1]
        (No symbol) [0x0018D04D]
        (No symbol) [0x001C28B9]
        (No symbol) [0x001C08CC]
        (No symbol) [0x001BE4CB]
        (No symbol) [0x001BD164]
        (No symbol) [0x001B32A6]
        (No symbol) [0x001D858C]
        (No symbol) [0x001B2BFF]
        (No symbol) [0x001D8804]
        (No symbol) [0x001EC9EB]
        (No symbol) [0x001D8386]
        (No symbol) [0x001B163C]
        (No symbol) [0x001B269D]
        GetHandleVerifier [0x005A9A22+2655074]
        GetHandleVerifier [0x0059CA24+2601828]
        GetHandleVerifier [0x003B8C0A+619850]
        GetHandleVerifier [0x003B7830+614768]
        (No symbol) [0x002A05FC]
        (No symbol) [0x002A5968]
        (No symbol) [0x002A5A55]
        (No symbol) [0x002B051B]
        BaseThreadInitThunk [0x76636BD9+25]
        RtlGetFullPathName_UEx [0x771A8FD2+1218]
        RtlGetFullPathName_UEx [0x771A8F9D+1165]

Message: element click intercepted: Element <a class="ds-card-sec ng-scope" ng-if="$ctrl.item.callToAction.text" aria-disabled="false" aria-label="Quiz expresso   Vous ne connaissez pas une réponse? Recherchez-la sur Bing!   30 points" tabindex="0" target="true" role="link">...</a> is not clickable at point (385, 400). Other element would receive the click: <div id="wcpConsentBannerCtrl" class="_23tra1HsiiP6cT-Cka-ycB" dir="ltr" role="alert">...</div>
  (Session info: headless chrome=108.0.5359.125)
Stacktrace:
Backtrace:
        (No symbol) [0x0030F243]
        (No symbol) [0x00297FD1]
        (No symbol) [0x0018D04D]
        (No symbol) [0x001C28B9]
        (No symbol) [0x001C08CC]
        (No symbol) [0x001BE4CB]
        (No symbol) [0x001BD164]
        (No symbol) [0x001B32A6]
        (No symbol) [0x001D858C]
        (No symbol) [0x001B2BFF]
        (No symbol) [0x001D8804]
        (No symbol) [0x001EC9EB]
        (No symbol) [0x001D8386]
        (No symbol) [0x001B163C]
        (No symbol) [0x001B269D]
        GetHandleVerifier [0x005A9A22+2655074]
        GetHandleVerifier [0x0059CA24+2601828]
        GetHandleVerifier [0x003B8C0A+619850]
        GetHandleVerifier [0x003B7830+614768]
        (No symbol) [0x002A05FC]
        (No symbol) [0x002A5968]
        (No symbol) [0x002A5A55]
        (No symbol) [0x002B051B]
        BaseThreadInitThunk [0x76636BD9+25]
        RtlGetFullPathName_UEx [0x771A8FD2+1218]
        RtlGetFullPathName_UEx [0x771A8F9D+1165]
Thank youy -_-

**Comment by NolanMastro** [comment]
Well, I'm not exactly sure what's it's failing at clicking, but it seems it could have been at a different page than it thought it was. I would recommend running it a few more times. Keep this issue open though, hopefully someone else can help.

**Comment by AinzOoalGown-fun** [comment]
it opens a chrome window, it works  desktop and mobile search works but the bot does not work with quizzes
![quizz](https://user-images.githubusercontent.com/73220716/210584468-a3e9ec23-8930-4cd7-b957-3a9206bb52cc.png)

**Comment by AinzOoalGown-fun** [comment]
it's in French

**Comment by AinzOoalGown-fun** [comment]
thank you NolanMastro for your help -_- , i'll leave it open for someone to help me.

**Comment by Prem-ium** [comment]
@AinzOoalGown-fun In this case, you have two quiz instances open and the program is likely trying to complete one while having a click being intercepted. You can manually click random quiz options on one of them (the dropdown or search quiz) & rerun the program.
