### ISSUE TITLE
Unable to locate element

### ISSUE THREAD

**Issue by Plus-xu** [Prem-ium/BingRewards#40]
**Environment:**

Location: USA
Debian 11 (x86_64)
Python 3.9.2
Chromium 108.0.5359.124
Chromedriver 108.0.5359.71
Run locally
https://github.com/Prem-ium/BingRewards/commit/fd0e306fda380d8387956f5bf5cf946d93711dd7
Defaults .env variables

**Errors:**

1. Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="idSIButton9"]"}
   (Session info: chrome=108.0.5359.124)

2. Traceback (most recent call last):
  File "/BingRewards/main.py", line 1145, in update_searches
    PC = driver.find_element(By.XPATH, value='//*[@id="userPointsBreakdown"]/div/div[2]/div/div[1]/div/div[2]/mee-rewards-user-points-details/div/div/div/div/p[2]').text.replace(" ", "").split("/")
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
**selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element:** {"method":"xpath","selector":"//*[@id="userPointsBreakdown"]/div/div[2]/div/div[1]/div/div[2]/mee-rewards-user-points-details/div/div/div/div/p[2]"}
  (Session info: chrome=108.0.5359.124)

3. Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="daily-sets"]/mee-card-group[1]/div/mee-card[1]/div/card-content/mee-rewards-daily-set-item-content/div/a/mee-rewards-points/div/div/span[1]"}
  (Session info: chrome=108.0.5359.124)

These type of error occurs frequently, and some quizzes or Daily Sets can not be completed.

**Comment by Seantourage** [comment]
Any news on how to fix this?
