### ISSUE TITLE
Implement password-less account handling?

### ISSUE THREAD

**Issue by erichobson** [Prem-ium/BingRewards#42]
This looks promising!

Just a quick suggestion, what would the possibility be of adding support for password-less accounts? I may look into this myself if I have time, but this could be a really useful feature for people that do not use passwords on their Microsoft account anymore.

**Comment by Prem-ium** [comment]
Hey @erichobson,

There are currently no plans to implement this unless another developer is interested in this & makes a pull request with new code. 

Thank you for your interest.
