### ISSUE TITLE
MSN shopping game

### ISSUE THREAD

**Issue by TatsP** [Prem-ium/BingRewards#43]
Please add the MSN Shopping Game, the below script provides the correct answer so we can use it. It will make the task easier. Please add the functionality as it results in 100 extra points daily per account.
https://www.msn.com/en-us/shopping
https://pastebin.com/Vrxpbh65

**Comment by Prem-ium** [comment]
I added an experimental feature for this supposed shopping game in the latest commit. I do not have access to this method of earning extra points as nothing shows up for me on the shopping link you've provided. The feature is optional and is not guaranteed to work as, again, I am unable to test it. You will need to verify it works by enabling SHOPPING in the env and creating a new issue with fixed code if you encounter bugs.

**Comment by TatsP** [comment]
> 

You can enable the shopping game by clearing cookies and cache as sometimes the game does not show as it works locally, the fix you've implemented does not work as it shows the correct answer but you will need to implement a method to make it click on the correct answer. Also please implement the fitness videos if possible as it gives 40 points extra per day per account.

**Comment by Prem-ium** [comment]
@TatsP I was unable to enable the shopping game even after clearing history, cookies, cache-- and even attempting to view it in incognito mode after signing in. Unless that changes, I won't be able to implement it.


Also, fitness videos takes are very long and as previously mentioned there's no plans to implement them as the videos usually only give credit for watching the entire 60+ minutes of content per account

**Comment by TatsP** [comment]
> @TatsP I was unable to enable the shopping game even after clearing history, cookies, cache-- and even attempting to view it in incognito mode after signing in. Unless that changes, I won't be able to implement it.
> 
> Also, fitness videos takes are very long and as previously mentioned there's no plans to implement them as the videos usually only give credit for watching the entire 60+ minutes of content per account

https://www.reddit.com/r/MicrosoftRewards/comments/wn1and/msn_fitness_hyper_optimization_i_aint_got_time_to/

The fitness videos mentioned in the above Reddit posts range hardly from 10 seconds to 5 minutes and reaching the 5 minutes mark is not possible as the short videos reset in 7 days. This makes it possible to earn 40 points daily for 5 minutes of watching 2 videos. Check it out once if possible.
