### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by gempath** [Prem-ium/BingRewards#44]
When running multiple accounts is it possible to have the accounts space out the timing of logging in instead of them all logging in at once?  Is it also possible to space out the timing of the searches?  It seems as if it is searching too fast.

**Comment by Prem-ium** [comment]
No, when running multi-threading, it will run all at once simultaneously. If you want to space them out, you should disable multithreading and let it them execute one-by-one. I have allowed users to adjust the amount of time between searches in the newest commit using DELAY_SEARCH env variable.
