### ISSUE TITLE
Cash value and points errors when using multiple accounts

### ISSUE THREAD

**Issue by yannikbaranski** [Prem-ium/BingRewards#45]
If you use mutiple accounts the points will only work with the first account.
![image](https://user-images.githubusercontent.com/88081269/213934804-81244012-6ffa-4a66-8f2c-d51b83c5675e.png)
![image](https://user-images.githubusercontent.com/88081269/213934823-be11d45a-b048-4deb-aa67-92a47e80f629.png)

**Comment by Prem-ium** [comment]
@yannikbaranski This could be because of many reasons such as a failure to load the page or unable to find the points XPATH element. In those cases -1 is intentionally sent to ensure the program executes searches, quizzes, etc.
