### ISSUE TITLE
main.py might has a typo?

### ISSUE THREAD

**Issue by MHYCWasTaken** [Prem-ium/BingRewards#46]
im new to python and when i run `python  ./main.py`
it told me
```
Traceback (most recent call last):
  File "W:\BingRewards\main.py", line 94, in <module>
    if (os.envion.get("SHOPPING", "false").lower() == "true"):
        ^^^^^^^^^
AttributeError: module 'os' has no attribute 'envion'. Did you mean: 'environ'?
```
so i tried to change it to environ, and the program run normaly  
so is that a typo or it is how it should be?

**Comment by Prem-ium** [comment]
You are correct! It was a typo. Thank you for catching that. Newest commit should fix it.
