### ISSUE TITLE
frozen OS error.

### ISSUE THREAD

**Issue by gc23485** [Prem-ium/BingRewards#50]
I'm not sure if this is as I'm UK based and it won't work for me, however this will not run. following setting up env file, and turning headless back off, it seems it's not even getting to opening a chrome window. Any ideas on what may be causing the below?

`Traceback (most recent call last):
  File "C:\Users\My Laptop\Desktop\BingRewards-main\main.py", line 29, in <module>
    if not os.environ["LOGIN"]:
           ~~~~~~~~~~^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: `'LOGIN``

**Comment by Prem-ium** [comment]
Make sure you have a `LOGIN' variable in your env. Seems to be an issue with your system.

**Comment by Southwestern12cat** [comment]
I'm having the same issue. Whenever I attempt to run it, it gives me the same thing. Here is what it looks like.

# Required .env variables:
# Comma delimited, remove quotes if using a single account
'LOGIN'= southwestern12cat@gmail.com:a2zwithme

# If you open up the Bing homepage in incognito mode and click the "Sign In" button. 
# Should take you to the login page, where you can copy the URL and assign it to the URL env variable. 
URL="https://login.live.com/login.srf?{QUERY}"

# Optional .env variables:
# Set WebDriver Download Manager status to on
# Default: True
# Values: True | False
HANDLE_DRIVER=True

# ** Experimental **
# Set the browser the bot will use.
# Not used in Docker
# HANDLE_DRIVER must be True
# Default: 'chrome'
# Values: 'chrome' | 'edge' | 'firefox'
BROWSER='chrome'

# Whether the program will run in headless mode [no ui]
# Default: False
# Values: True | False
HEADLESS=False

# Whether the program will run multiple threads to run all accounts or not
# Default: False
# Values: True | False
MULTITHREADING=False

# How long to wait before performing searches
# Values: Any valid integer
DELAY_SEARCH=10

# Configure Apprise URL Alerts
# Full list of available URLs
#   https://github.com/caronc/apprise/wiki
# Default:
# Values: Any Apprise URL
APPRISE_ALERTS=

# Auto-Redeem rewards
# Default: False
# Values: True | False
AUTO_REDEEM=False

# Set the goal automatically
# Default: 'amazon.com'
# Values: 'amazon.com' | 'hulu' | 'walmart'
GOAL='amazon.com'

# Whether the bot should automate punchcards
# Default: False
# Values: True | False
AUTOMATE_PUNCHCARD=True

# ** Experimental **
# Attemptes to create a new shoping feature
# 
# No contributing developer has access to this method
# of points to verify/debug functionality
# Default: False
# Values: True | False
SHOPPING=False

# Sets the currency symbol or name
# Plan to add more as more users provide information on their local conversion rates.
# Default: USD
# Values: $ | USD | € | EURO
CURRENCY=USD

# Name of the instance of the bot
# Default: 'Bing Rewards Automation'
# Values: Any String, single-quoted if name contains spaces or special characters
BOT_NAME='Bing Rewards Automation'

# Sets the timezone for the bot
# Default: 'America/New_York'
# Values: Any valid IANA timezone (https://www.iana.org/time-zones)
TZ='America/New_York'

# Enables / Disables the timer functionality
# Default: False
# Values: True | False
TIMER=False

# What time the bot will function
#
# Use 1-24 to set time, such as 4 being 4:00AM, 13 being 1:00PM
# Default:
#   START_TIME: 4
#   END_TIME: 19
# Values: 1-24
START_TIME=4
END_TIME=19

# Whether you want to use a flask server to prevent the program
# from dying
#
# Default: False
# Values: True | False
KEEP_ALIVE=False

# Your desired external IPv4 Address
# Optional
# If you do not want to check your external IPv4 address
# is the same as your desired IPv4 address
# Default: 
# Values: Any valid IPv4 Address
WANTED_IPV4=

# Your desired external IPv6 Address
# Optional
# If you do not want to check your external IPv6 address
# is the same as your desired IPv6 address
# Default: 
# Values: Any valid IPv6 Address
WANTED_IPV6=

# Configure a HTTP(S) or SOCKS5 proxy through which all of the bot's traffic will go
# Default:
# Values: Any valid URI format proxy (e.g., https://1.2.3.4:5678)
PROXY=https://10.10.10.10:8000
