### ISSUE TITLE
no definied modul with flask

### ISSUE THREAD

**Issue by badplay** [Prem-ium/BingRewards#52]
hi
i have installed the request and python 3.7.9 i need 3.7.9 for something elese. normally all works well
but when i start the bot i get message

Traceback (most recent call last):
  File "C:\Users\Bre\folder1\BingRewards\main.py", line 85, in <module>
    from keep_alive import keep_alive
  File "C:\Users\Bre\folder1\BingRewards\keep_alive.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
>>> 

my .env looks like:
# Required .env variables:
LOGIN="mike__hendrik@hotmail.com:sdgterh9efh84zjgfd,olfheinike@hotmail.com:hein38dgnsq#"

# If you open up the Bing homepage in incognito mode and click the "Sign In" button. 
# Should take you to the login page, where you can copy the URL and assign it to the URL env variable. 
URL="https://login.live.com/oauth20_a"

# Optional .env variables:

HANDLE_DRIVER= True
BROWSER= chrome
HEADLESS= False

MULTITHREADING= False

DELAY_SEARCH= 2

AUTOMATE_PUNCHCARD= True

SHOPPING = True

CURRENCY= €

BOT_NAME = 'bing rewards 3'

TZ= CEST
TIMER= False
START_TIME= 4
END_TIME= 19

KEEP_ALIVE = True  

# Configure a HTTP(S) or SOCKS5 proxy through which all of the bot's traffic will go
# Should be in a URI format (e.g., https://1.2.3.4:5678)
#PROXY=

**Comment by Prem-ium** [comment]
The exception is happening because you enabled the KEEP_ALIVE env variable but your machine doesn’t have Flask installed.

You can fix it by installing the latest commit requirements.txt or using ‘pip install Flask’
