### ISSUE TITLE
the super speed quiz don't work

### ISSUE THREAD

**Issue by ItzMeDiego** [Prem-ium/BingRewards#58]
hi, the bot is doing all well but for every of my accounts the superspeed quiz is not complete.
in more (i use edge) the bot block himself because the browser require every time for cookies  acconsention

**Comment by kaishi961125** [comment]
Indicates what error

**Comment by ItzMeDiego** [comment]
it don't have a precise error

**Comment by Seantourage** [comment]
It's the warp speed quiz on the dailies that isn't completing. Not sure if this console output helps or is even related:

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 1169, in update_searches
    PC = driver.find_element(By.XPATH, value='//*[@id="userPointsBreakdown"]/div/div[2]/div/div[1]/div/div[2]/mee-rewards-user-points-details/div/div/div/div/p[2]').text.replace(" ", "").split("/")
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="userPointsBreakdown"]/div/div[2]/div/div[1]/div/div[2]/mee-rewards-user-points-details/div/div/div/div/p[2]"}
  (Session info: chrome=109.0.5414.119)
Stacktrace:
#0 0x5568a8cba303 <unknown>
#1 0x5568a8a8ed37 <unknown>
#2 0x5568a8acb5b2 <unknown>
#3 0x5568a8acb6c1 <unknown>
#4 0x5568a8b05b34 <unknown>
#5 0x5568a8aeb9ad <unknown>
#6 0x5568a8b0388c <unknown>
#7 0x5568a8aeb753 <unknown>
#8 0x5568a8abea14 <unknown>
#9 0x5568a8abfb7e <unknown>
#10 0x5568a8d0932e <unknown>
#11 0x5568a8d0cc0e <unknown>
#12 0x5568a8cef610 <unknown>
#13 0x5568a8d0dc23 <unknown>
#14 0x5568a8ce1545 <unknown>
#15 0x5568a8d2e6a8 <unknown>
#16 0x5568a8d2e836 <unknown>
#17 0x5568a8d49d13 <unknown>
#18 0x7fe0074c1b43 <unknown>
	1 PC search of 34. Now 2% done.`

**Comment by ItzMeDiego** [comment]
i mean the quiz don't start because edge request for the cookies allowance and the bot don't accept it automatically
