### ISSUE TITLE
Can the Docker version support linux/arm64/v8

### ISSUE THREAD

**Issue by OwnerCM** [Prem-ium/BingRewards#68]
Can the Docker version support Linux/arm64/v8 platform。
ERROR：
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /app/entrypoint.sh: exec format error

**Comment by 3lf-dev** [comment]
I'm afraid that's unlikely. In my own experience, I had to manually install it on my Raspberry Pi without relying on Docker or any virtualization software. It appears that the root of the issue lies with the '/app/entrypoint.sh' file, which doesn't seem to be compatible with the arm64 architecture.
