### ISSUE TITLE
KeyError: 'LOGIN'

### ISSUE THREAD

**Issue by SingingDwarf** [Prem-ium/BingRewards#69]
Running docker container on Ubunutu, I get the following error:

```
Starting X virtual framebuffer (Xvfb) in background...

 
HANDLE_DRIVER: 
Starting Bing Rewards Bot...
Traceback (most recent call last):
  File "/app/main.py", line 30, in <module>
    if not os.environ["LOGIN"]:
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOGIN'
```
Not quite sure where to go from here?

**Comment by SingingDwarf** [comment]
Appears to be a similar issue to #60 - I do not have any strange characters in my login password.

**Comment by SingingDwarf** [comment]
Appears to be a similar issue to #60 - I do not have any strange characters in my login password.

**Comment by lab596** [comment]
Refer to #60 make sure you change the original url provided in .env to microsoft login. Im not sure why it is not originally placed there in the source code...
