### ISSUE TITLE
notwoking in crontab

### ISSUE THREAD

**Issue by bscongluanbui** [Prem-ium/BingRewards#72]
Hi, I using ubuntu 22.04 run it in normal terminal. But when I using crontab for autorun, It's not working.  its said about package chromium
[output.txt](https://github.com/Prem-ium/BingRewards/files/11175004/output.txt)
this is output log.

**Comment by meghrathod** [comment]
Here is a sample crontab that works at every machine restart, it works just fine, try to model yours based off this

```sh
@reboot /usr/bin/tmux new-session -d -s bing 'cd ~/BingRewards && /usr/bin/python3 main.py'
```

to view the logs you can enter the tmux session with the below command
```sh
$ tmux a -t bing
```

**Comment by bscongluanbui** [comment]
thank you. I will try this
