### ISSUE TITLE
[Help] practical tutorial

### ISSUE THREAD

**Issue by fabiovieitas** [Prem-ium/BingRewards#78]
good morning! Please help me!!!

I don't know how to install. could you give me a practical tutorial????

Thanks in advance!!!

**Comment by meghrathod** [comment]
The steps for running are mentioned in the README. There is no video as such, if that's what you're asking.

**Comment by fabiovieitas** [comment]
> As etapas para execução são mencionadas no README. Não há vídeo como tal, se é isso que você está perguntando.

Thank you for your attention. Unfortunately I don't know how to start the installation, even reading the "readme".

**Comment by meghrathod** [comment]
Sorry but if you're looking for a Youtube tutorial, there ain't one.
