### ISSUE TITLE
The final mobile search does not count somehow

### ISSUE THREAD

**Issue by SiriusArc7** [Prem-ium/BingRewards#81]
Does anyone here have a problem that the last mobile search does not count somehow and remains unfinished? 

I live in Japan where POINTS_PER_SEARCH is 3 so it may not be the case for most of the contributors here, but every time the python script runs, it always finishes the mobile search with 57/60. After several hours the next attempt happens as usual and it detects that 1 mobile search has to be done... but it ends up 57/60 somehow even though the script does 1 mobile search. It's just NOT counting.
The weird thing is that PC search always works successfully(90/90) so I assume there's something different needed on mobile specifically but I need to know if this is only happening to me. If someone else is having this issue, I will try to fix this and make a PR. Thanks

**Comment by amaan14999** [comment]
Yes. I have the same issue. But from what I have noticed, sometimes it does complete the last search but most of the time it doesn't.

**Comment by SiriusArc7** [comment]
@amaan14999 Thanks for your info! Is your POINTS_PER_SEARCH = 3 too or a different value?

I've managed to overcome this problem by simply doing an additional mobile search, but I'm not really sure it's worth creating a pull request...

**Comment by amaan14999** [comment]
No, my points per search is 5. I too do an additional search.

**Comment by SiriusArc7** [comment]
@amaan14999 Hmm, so it seems like the region or POINTS_PER_SEARCH is not the core of this issue :/
I'm going to make a PR with minimal change. Thanks for your response again!
