### ISSUE TITLE
Mobile Searches not working in India

### ISSUE THREAD

**Issue by amaan14999** [Prem-ium/BingRewards#93]
The code executes and searches for mobile searches, but the points don't add up in the total points. This happens only when I execute the code in India. On my VM in the US, it works perfectly fine.

**Comment by Prem-ium** [comment]
Unfortunately, I am unable to debug or test a solution for this as I am based in the USA. However, I know Bing sometimes tends not to credit for some searches-- I am not entirely sure if it is because of geographic location.
