### ISSUE TITLE
Friendly Notice: All my accounts were suspended

### ISSUE THREAD

**Issue by SiriusArc7** [Prem-ium/BingRewards#96]
It's actually not an issue and I'm not even complaining, but I'd leave a note here to hopefully help you from getting banned.
I ran this script on 5 accounts (the max number mentioned in the env file) for approx. 6 months, but they were all confirmed suspended today. I did not change the interval values for every attempt. It was fortunate that I had redeemed amazon gift cards recently so not so many points were lost in vain... but things like this just happen.

I will try if it's possible to reuse the phone numbers just for fun(because phone numbers are finite resources!) in completely different environments sooner or later, but I will no longer contribute to the project. Thanks.

**Comment by Prem-ium** [comment]
I'm so sorry to hear that! These things happen, however I am able to confirm you should be able to reuse a phone number a few weeks/months after the suspension if you close the account. You can always create new Bing Rewards account to use, so far I haven't ran into any issues doing so.

**Comment by SiriusArc7** [comment]
Oh, it's great to hear that we can reuse phone numbers! I'll be away for developing for a while anyway because it's getting busy here, but I've gained my motivation once again!
