### ISSUE TITLE
help!!

### ISSUE THREAD

**Issue by lg-yyds** [Prem-ium/BingRewards#98]
![image](https://github.com/Prem-ium/BingRewards/assets/68491005/48da36ed-1957-4f63-b8c4-280aed9cf28b)
Starting X virtual framebuffer (Xvfb) in background...
BROWSER: 'edge'
HANDLE_DRIVER: True
Starting Bing Rewards Bot...
Traceback (most recent call last):
  File "/app/main.py", line 136, in <module>
    TZ = timezone(os.environ.get("TZ", "America/New_York"))
  File "/usr/local/lib/python3.10/dist-packages/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: "'Asia/Seoul'"

**Comment by Prem-ium** [comment]
Copy and paste this into your ```.env``` file. I tried to replicate your bug, but mine successfully used Seoul time-zone. 
```
TZ=Asia/Seoul
```
